name: Déploiement Angular webapp sur Synology NAS

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build de l'application
    runs-on: ubuntu-latest
    steps:
      - name: Récupération du code
        uses: actions/checkout@v3

      - name: Installation de Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22.14"

      - name: Installation des dépendances
        run: npm ci

      - name: Build de l'application Angular
        run: npm run build

      - name: Archivage du build
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: dist/

  deploy:
    name: Déploiement sur le NAS
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Téléchargement de l'archive du build
        uses: actions/download-artifact@v4
        with:
          name: build
          path: dist

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          printf "%s" "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p ${{ secrets.SSH_PORT }} -H ${{ secrets.SYNOLOGY_HOST }} >> ~/.ssh/known_hosts
      - name: Verify SSH key
        run: ls -lah ~/.ssh && file ~/.ssh/id_rsa

      - name: Tester la connexion SSH au NAS
        run: |
          ssh -vvv -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ secrets.SYNOLOGY_USER }}@${{ secrets.SYNOLOGY_HOST }} -p ${{ secrets.SSH_PORT }} "echo 'Connexion SSH réussie'"
      - name: Add SSH Host to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p ${{ secrets.SSH_PORT }} -H ${{ secrets.SYNOLOGY_HOST }} 2>/dev/null >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
      - name: Déploiement sur Synology via SCP
        uses: appleboy/scp-action@v0.1.5
        with:
          host: ${{ secrets.SYNOLOGY_HOST }}
          username: ${{ secrets.SYNOLOGY_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "dist/"
          target: ${{ secrets.TARGET_PATH }}
